version: "3.5"
services:
  nodejs:
    build: .
    env_file: .env
    container_name: "gerald-test"
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "3000:8080"